### PR TITLE
support for time series using Base.Dates added closes #36

### LINKED ISSUE #36: Support plotting time series
Something along the lines of ...
````
function lineplot{T<:TimeType,R<:Real}(X::AbstractVector{T}, Y::AbstractVector{R};
````
This would require importing the `Base.Dates` package.

### PR DESCRIPTION
**Pull request by milktrader**
Sorry for the previous noise, you've done quite a bit of work since last I pulled this repo.

### CODE REVIEW

**Comment by milktrader** [comment]
screen shot 2015-11-01 at 6 07 41 pm

**Comment by Evizero** [comment]
Looks great! No worries. I'm happy that people are interested in using and improving this package.

**Comment by Evizero** [comment]
how did you create that plot, could you give me some minimal example?

**Comment by milktrader** [comment]
````julia

julia> using MarketData, UnicodePlots

julia> d = cl.timestamp; v = cl["Close"].values;

julia> lineplot(d,v)
````

**Comment by milktrader** [comment]
This one is simpler ....
````julia
julia> d = [Date(2000,1,1):Date(2000,1,31)];

julia> v = [linspace(20, 200, 31)];

julia> lineplot(d,v)
````

screen shot 2015-11-01 at 6 28 43 pm

**Comment by Evizero** [comment]
nice! I am a little confused why your top border is blue. does it go away if you specify a title?

**Comment by Evizero** [comment]
anyhow, thanks for the contribution! (and for sticking with it)

**Comment by milktrader** [comment]
Yes, a title fixes it.
screen shot 2015-11-01 at 6 53 40 pm

**Pull request merged**
