### PR TITLE
Julia 07 fixes

### PR DESCRIPTION
**Pull request by Paulms**
Fix Julia v0.7 warnings and deprecations

### CODE REVIEW

**Comment by Evizero** [comment]
Thanks for tackling this! 

That said, I'm afraid it will take me a bit before i can review and merge this, as I have not started the migration process and thus don't quite know much about 0.7 yet

**Comment by Paulms** [comment]
Ok, no problem, take your time.

**Comment by KristofferC** [comment]
I wouldn't recommend commiting the Manifest file here.

**Comment by Paulms** [comment]
Ok, I remove the Manifest file, but now I get some  MethodError: no method matching haskey(::Nothing, ::String) related with _get_deps! on Travis. It seems extrange that for Julia nightly travis works (since I assume nigthly is also Julia 0.7 beta). All test are passed on my local machine so I am not sure if it is a temporary problem with travis.

**Comment by KristofferC** [comment]
Beta is significantly behind nightly at this point. I would focus on getting test passing on nightly for now.

**Comment by Evizero** [comment]
Thanks!

**Pull request merged**
