### PR TITLE
add support for plotting Date and DateTime closes #36

### LINKED ISSUE #36: Support plotting time series
Something along the lines of ...
````
function lineplot{T<:TimeType,R<:Real}(X::AbstractVector{T}, Y::AbstractVector{R};
````
This would require importing the `Base.Dates` package.

### PR DESCRIPTION
**Pull request by milktrader**
The color variable might need to be tweaked ...

### CODE REVIEW

**Comment by milktrader** [comment]
Didn't have the blue line on the top of the canvas earlier ...

screen shot 2015-11-01 at 5 30 58 pm

**Comment by Evizero** [comment]
I'm a little confused. It seems again that your commit is based on a really old commit from August. Could it be that your local git history of UnicodePlots is messed up?

**Comment by Evizero** [comment]
I'd love to merge that code as your contribution if you want to stick with it. But if you are getting tired of messing with git (I'm not sure what's going on either) I'm ok with copying the code and giving you credit with a comment similar to [here](https://github.com/Evizero/UnicodePlots.jl/blob/master/src/interface/histogram.jl)

**Comment by Evizero** [comment]
It looks like your date branch is 83 commits behind master.

**Comment by milktrader** [comment]
whoa, let me give it one more shot ...

**Pull request closed without merging**
