### PR TITLE
Fix InexactError() bug

### PR DESCRIPTION
**Pull request by lopezm94**
Fix for #51, tested it with random inputs for a while a worked like a charm.

### CODE REVIEW

**Comment by lopezm94** [comment]
Is the only way to not get the error is to install the master branch? or can the PR somehow propagate to a previous release?

**Comment by Evizero** [comment]
can you maybe add your previous call that caused the error into the (very messy and unprofessional) test file?

As soon as I merge I will tag a new version, so no you won't have to checkout the master

**Comment by lopezm94** [comment]
I couldn't help but chuckle at your test cases, I tried to mimic your test theme as much as I could. 

I also added some more round checks in common.jl just in case.

**Comment by lopezm94** [comment]
I don't really understand coveralls, but if you want I can try to fix that

**Comment by Evizero** [comment]
Thanks! No don't mind coverall. One day I will have to think of actual sensible testing (Turns out testing a terminal plotting library is not that easy)

**Comment by Evizero** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/5764

**Pull request merged**
