### PR TITLE
Relax type for spy plots

### PR DESCRIPTION
**Pull request by jakebolewski**
An implementation of `findnz` is really all that is required for an `AbstractArray` implementation.

### CODE REVIEW

**Comment by Evizero** [comment]
Make sense, thank you!

Could you maybe include `print(spy(full(sprand(100,100,.15))))` somewhere near line 170 of the tst_plots file just to make sure it at least compiles. (I know that file is a mess, please don't judge me)

**Comment by jakebolewski** [comment]
Sure, you win :heart:s with this package.  As a favor, could you tag a new version?  I may need for someone to use this in a demo tomorrow.

**Comment by Evizero** [comment]
Thank you. Ok, sure I don't mind. As soon as the check completes I'll merge and submit a tag

**Comment by Evizero** [comment]
Submitted the Tag to [METADATA](https://github.com/JuliaLang/METADATA.jl/pull/3402).
I know though if it will me merged by tomorrow.

**Pull request merged**
